server:
  port: 8181
  
  
spring: 

  zipkin:
    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:   
    
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true 
  
  
  logging:
   file: D:/microservice.log
  
 
       
 
     
  application:
    name: ORDER-SERVICE